# Site settings
title: Paul Moncenix-Larue
email: paul.moncenix@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Portfolio de Paul Moncenix-Larue, étudiant en BUT Informatique à l'IUT2 de Grenoble. Présentation de projets en développement web, logiciels, et data, réalisés dans un cadre universitaire et personnel. Compétences en conception, programmation, validation, et gestion de projet."
keywords: "Paul Moncenix-Larue, portfolio, BUT Informatique, IUT2 Grenoble, étudiant informatique, développement web, projets étudiants, développement logiciel, Symfony, React, C++, PHP, JavaScript, SQL, informatique Grenoble"
skills: "BUT2 Informatique - Parcours réalisation d'applications: conception, développement, validation"
meta_author: Moncenix-Larue Paul

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3badd1 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Paul Moncenix-Larue
  location: Adresse
  social: Retrouvez moi sur
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/paul-moncenix-larue-5995a4215/
  - title: github
    url: http://github.com/pmoncenix

# Postal address (add as many lines as necessary)
address:
  - line: 118 Impasse des Colombes
  - line: 38570, Theys

# Credits content
credits: 'Blackrock Digital LLC, LitoMore, <br> Paul Moncenix-Larue'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
